#!/bin/bash
HARNESS_ROOT="${HARNESS_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
OPENCLAW_HOME="${OPENCLAW_HOME:-$HOME/.openclaw}"
OPENCLAW_WORKSPACE="${OPENCLAW_WORKSPACE:-$OPENCLAW_HOME/workspace}"
# build-manager-memory.sh
# Generates $OPENCLAW_WORKSPACE/MEMORY.md from harness source files.
# Run at turn-end after editing any memory file.
# Output is ~8KB max; recognized bootstrap basename so OpenClaw injects it automatically.

set -euo pipefail

HARNESS_MEM="$HARNESS_ROOT/memory"
WORKSPACE_MEM="$OPENCLAW_WORKSPACE/MEMORY.md"
MAX_BYTES=12000

TODOS="$HARNESS_MEM/todos.md"
DECISIONS="$HARNESS_MEM/decisions.md"
SCRATCH="$HARNESS_MEM/scratch.md"

build() {
  echo "<!-- GENERATED by build-manager-memory.sh — do not hand-edit -->"
  echo "<!-- Source: $HARNESS_MEM — edit source files, then re-run this script -->"
  echo ""
  printf '# Manager Memory\n'
  printf '_Generated: %s_\n\n' "$(date '+%Y-%m-%d %H:%M')"

  # MOST CRITICAL FIRST (survives the byte cap): current state, then todos,
  # then recent decisions last (least time-critical; truncated if over budget).

  # scratch.md: current working state (## Active task section, else last ~40 lines)
  printf '## Current state (scratch)\n'
  if [ -f "$SCRATCH" ]; then
    ACTIVE=$(awk '
      /^## Active task/ { found=1 }
      found { print }
      /^## / { if (found && !/^## Active task/) exit }
    ' "$SCRATCH")
    if [ -n "$ACTIVE" ]; then
      printf '%s\n' "$ACTIVE"
    else
      tail -n 40 "$SCRATCH"
    fi
  else
    echo "(scratch.md not found)"
  fi
  printf '\n'

  # todos.md: full
  printf '## Active Todos\n'
  if [ -f "$TODOS" ]; then
    cat "$TODOS"
  else
    echo "(todos.md not found)"
  fi
  printf '\n'

  # decisions.md: last 12 lines (context; first to be cut if over budget)
  printf '## Recent Decisions\n'
  if [ -f "$DECISIONS" ]; then
    tail -n 12 "$DECISIONS"
  else
    echo "(decisions.md not found)"
  fi
  printf '\n'
}

build | head -c "$MAX_BYTES" > "$WORKSPACE_MEM"

WRITTEN=$(wc -c < "$WORKSPACE_MEM")
echo "[build-manager-memory] wrote $WORKSPACE_MEM ($WRITTEN bytes)"
